services:
  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: safar_postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
