apiVersion: apps/v1
kind: Deployment
metadata:
  name: safar-driver-deployment
  labels:
    app: safar-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safar-driver
  template:
    metadata:
      labels:
        app: safar-driver
    spec:
      containers:
      - name: driver-container
        image: us-central1-docker.pkg.dev/project-b054c456-52e8-4026-af3/my-repo/driver-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5175
        envFrom:
        - secretRef:
            name: driver-env
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
      restartPolicy: Always
